#!/usr/bin/perl

use strict;
use warnings;

use Global qw(/./);
use Query qw(/./);
use Data::Dumper;

my $task = Query::resolveTask($ARGV[0]) or die help();

my $url = undef;

if(not defined $url) {
  my @external = map { $_->{'external'} } @{dbh()->selectall_arrayref(<<EOSQL, { Slice => {} }, $task->{'id'})};
  SELECT external FROM task_external WHERE task = ?
EOSQL

  foreach my $ext (@external) {
    if($ext =~ m!^redmine://(.*)!) {
      $url = "https://$1";
      last;
    }
  }
}

if(not defined $url and $task->{'title'} =~ /^(http[^ ]+)/) {
  $url = $1;
}

if(defined $url) {
  system("iceweasel '$url'");
  system("wmiir xwrite /ctl view 'www'");
}

sub help {
  return <<EOTXT
./act <task gid / 'c'>

Tries to switch computer context into helpful state for the task.
EOTXT
}
