#!/bin/zsh

file="$1"

{
  if [ "$file" = "" ]; then
    cat
  else
    cat "$file"
  fi
} | grep '^Subject:' | head -n 1 | sed -e 's/.*: *//' | tr -d "\r\n" | read subject;

todospec="$(zenity --entry --text="Bearbeite '${subject}' <util>, <time>")"
if [ "$todospec" != "" ]; then
  u="$(echo $todospec | sed -e 's/,.*//g')"
  t="$(echo $todospec | sed -e 's/.*, *//g')"
  zenity --info --text="$(cd /home/drahflow/utilator/perl && ./create "Mail '${subject}' bearbeiten" "$u" "$t" 2>&1)"
fi
