#!/usr/bin/perl

use strict;
use warnings;
use encoding 'utf-8';

use Global qw(/./);

my $gid = create_gid();
my $author = 'mailto://drahflow@gmx.de';
my $title = $ARGV[0] or die help();
my $utility = $ARGV[1] or die help();
my $seconds_estimate = interpretUnit($ARGV[2]) or die help();
my $publication = PUBLICATION_PRIVATE;
my $now = iso_full_date(time);

dbh()->do(<<EOSQL, {}, $gid, $author, $title, $seconds_estimate, 0, 0, $publication, $now);
INSERT INTO task (gid, author, title, seconds_estimate, seconds_taken, status, publication, last_edit) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
EOSQL

my $id = dbh()->selectall_arrayref(<<EOSQL, { Slice => {} }, $gid)->[0]->{'id'};
SELECT id FROM task WHERE gid = ?
EOSQL

dbh()->do(<<EOSQL, {}, $id, "0constant:" . int($utility * 1000));
INSERT INTO task_utility (task, distribution) VALUES (?, ?)
EOSQL

dbh()->do(<<EOSQL, {}, $gid);
UPDATE task_edit_last SET gid = ?
EOSQL

dbh()->disconnect();

print "$gid\n";

sub help {
  return <<EOTXT
create <title> <utility> <time estimate>
EOTXT
}
