#!/usr/bin/perl

BEGIN { push @INC, '.'; }

use strict;
use warnings;
use utf8;

use Global qw(/./);
use Query qw(/./);
use Data::Dumper;

my $task = Query::resolveTask($ARGV[0]) or die help();

my @fields = @ARGV[1 .. $#ARGV];

foreach my $field (@fields) {
  print "$task->{$field}\n";
}


unless (@fields) {
  print Dumper($task);
  print "Time est: " . reverseInterpretUnit($task->{'seconds_estimate'}) . "\n";

  print "\n-- utility --\n";
  print Dumper(dbh()->selectall_arrayref(<<EOSQL, { Slice => {} }, $task->{'gid'}));
  SELECT u.distribution, u.task FROM task_utility u JOIN task t ON t.id = u.task WHERE t.gid = ?
EOSQL

  my @evaluatedTasks = Query::sortedTasks(iso_full_date(time));
  my ($evaluatedTask) = grep { $_->{'id'} eq $task->{'id'} } @evaluatedTasks;
  print "Current utility: " . $evaluatedTask->{'current_utility'} * 3600 . " u/h\n";

  print "\n-- likelyhood time --\n";
  print Dumper(dbh()->selectall_arrayref(<<EOSQL, { Slice => {} }, $task->{'gid'}));
  SELECT l.distribution, l.task FROM task_likelyhood_time l JOIN task t ON t.id = l.task WHERE t.gid = ?
EOSQL

  print "\n-- likelyhood space --\n";
  print Dumper(dbh()->selectall_arrayref(<<EOSQL, { Slice => {} }, $task->{'gid'}));
  SELECT l.distribution, l.task FROM task_likelyhood_space l JOIN task t ON t.id = l.task WHERE t.gid = ?
EOSQL

  print "\n-- external --\n";
  print Dumper(dbh()->selectall_arrayref(<<EOSQL, { Slice => {} }, $task->{'gid'}));
  SELECT e.external, e.task FROM task_external e JOIN task t ON t.id = e.task WHERE t.gid = ?
EOSQL

  print "\n-- expectation effects --\n";
  print Dumper(dbh()->selectall_arrayref(<<EOSQL, { Slice => {} }, $task->{'gid'}));
  SELECT te.effect, e.gid, e.title FROM task_effect te JOIN expectation e ON e.id = te.expectation JOIN task t ON t.id = te.task WHERE t.gid = ?
EOSQL
}

sub help {
  return <<EOTXT
dump <task> [<field>...]
EOTXT
}
