#!/usr/bin/perl

use strict;
use warnings;
use encoding 'utf-8';
use lib '/var/www/utilator';

use Global qw(dbh);
use Data::Dumper;

my $stuff;
my $len = read(STDIN, $stuff, $ENV{'CONTENT_LENGTH'});

