#!/usr/bin/perl

BEGIN { push @INC, '.'; }

use strict;
use warnings;
use utf8;

use Global qw(/./);
use Synchronize qw(/./);
use JSON;

my $input = join '', <STDIN>;

if($input ne '') {
  $input = decode_json($input);
} else {
  $input = { 'task' => [] };
}

print encode_json(Synchronize::sync($input, 0));
